import type { ScriptureReading } from '@/lib/content/types';

export const week1FridayIsaiah: ScriptureReading = {
  id: 'week1-friday-isaiah',
  citation: 'Isaiah 3:1-14',
  translationSource: 'KJV',
  fullText: `For, behold, the Lord, the LORD of hosts, doth take away from Jerusalem and from Judah the stay and the staff, the whole stay of bread, and the whole stay of water, The mighty man, and the man of war, the judge, and the prophet, and the prudent, and the ancient, The captain of fifty, and the honourable man, and the counsellor, and the cunning artificer, and the eloquent orator. And I will give children to be their princes, and babes shall rule over them. And the people shall be oppressed, every one by another, and every one by his neighbour: the child shall behave himself proudly against the ancient, and the base against the honourable. When a man shall take hold of his brother of the house of his father, saying, Thou hast clothing, be thou our ruler, and let this ruin be under thy hand: In that day shall he swear, saying, I will not be an healer; for in my house is neither bread nor clothing: make me not a ruler of the people. For Jerusalem is ruined, and Judah is fallen: because their tongue and their doings are against the LORD, to provoke the eyes of his glory. The shew of their countenance doth witness against them; and they declare their sin as Sodom, they hide it not. Woe unto their soul! for they have rewarded evil unto themselves. Say ye to the righteous, that it shall be well with him: for they shall eat the fruit of their doings. Woe unto the wicked! it shall be ill with him: for the reward of his hands shall be given him. As for my people, children are their oppressors, and women rule over them. O my people, they which lead thee cause thee to err, and destroy the way of thy paths. The LORD standeth up to plead, and standeth to judge the people. The LORD will enter into judgment with the ancients of his people, and the princes thereof: for ye have eaten up the vineyard; the spoil of the poor is in your houses.`,
  paschaOffset: -44,
};
