import type { ScriptureReading } from '@/lib/content/types';

export const week1TuesdayIsaiah: ScriptureReading = {
  id: 'week1-tuesday-isaiah',
  citation: 'Isaiah 1:19-2:3',
  translationSource: 'KJV',
  fullText: `If ye be willing and obedient, ye shall eat the good of the land: But if ye refuse and rebel, ye shall be devoured with the sword: for the mouth of the LORD hath spoken it. How is the faithful city become an harlot! it was full of judgment; righteousness lodged in it; but now murderers. Thy silver is become dross, thy wine mixed with water: Thy princes are rebellious, and companions of thieves: every one loveth gifts, and followeth after rewards: they judge not the fatherless, neither doth the cause of the widow come unto them. Therefore saith the Lord, the LORD of hosts, the mighty One of Israel, Ah, I will ease me of mine adversaries, and avenge me of mine enemies: And I will turn my hand upon thee, and purely purge away thy dross, and take away all thy tin: And I will restore thy judges as at the first, and thy counsellors as at the beginning: afterward thou shalt be called, The city of righteousness, the faithful city. Zion shall be redeemed with judgment, and her converts with righteousness. And the destruction of the transgressors and of the sinners shall be together, and they that forsake the LORD shall be consumed. For they shall be ashamed of the oaks which ye have desired, and ye shall be confounded for the gardens that ye have chosen. For ye shall be as an oak whose leaf fadeth, and as a garden that hath no water. And the strong shall be as tow, and the maker of it as a spark, and they shall both burn together, and none shall quench them. The word that Isaiah the son of Amoz saw concerning Judah and Jerusalem. And it shall come to pass in the last days, that the mountain of the LORD's house shall be established in the top of the mountains, and shall be exalted above the hills; and all nations shall flow unto it. And many people shall go and say, Come ye, and let us go up to the mountain of the LORD, to the house of the God of Jacob; and he will teach us of his ways, and we will walk in his paths: for out of Zion shall go forth the law, and the word of the LORD from Jerusalem.`,
  paschaOffset: -47,
};
